const sampleListing = [
    {
        title: "Sea View Villa",
        description: "Beautiful villa with ocean view and private pool.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
        price: 3500,
        location: "Calangute, Goa",
        country: "India",
    },
    {
        title: "Mountain Cabin",
        description: "Cozy wooden cabin surrounded by pine forest.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        price: 1800,
        location: "Manali, Himachal Pradesh",
        country: "India",
    },
    {
        title: "City Apartment",
        description: "Modern apartment in city center with metro access.",
        image: "https://images.unsplash.com/photo-1493666438817-866a91353ca9",
        price: 2200,
        location: "Bangalore, Karnataka",
        country: "India",
    },
    {
        title: "Desert Camp Stay",
        description: "Traditional camp stay with cultural night experience.",
        image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1",
        price: 1400,
        location: "Jaisalmer, Rajasthan",
        country: "India",
    },
    {
        title: "Lake House",
        description: "Peaceful stay by the lake with boating included.",
        image: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
        price: 2700,
        location: "Udaipur, Rajasthan",
        country: "India",
    },
    {
        title: "Tea Garden Cottage",
        description: "Scenic cottage near tea estates and waterfalls.",
        image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
        price: 1600,
        location: "Munnar, Kerala",
        country: "India",
    },
    {
        title: "Snow Peak Chalet",
        description: "Warm chalet with fireplace and mountain sunrise view.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
        price: 3100,
        location: "Auli, Uttarakhand",
        country: "India",
    },
    {
        title: "Backwater Houseboat",
        description: "Private houseboat stay with local Kerala cuisine.",
        image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        price: 2900,
        location: "Alleppey, Kerala",
        country: "India",
    },
    {
        title: "Heritage Haveli",
        description: "Royal style rooms in a restored heritage property.",
        image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
        price: 4200,
        location: "Jaipur, Rajasthan",
        country: "India",
    },
    {
        title: "Cliffside Cottage",
        description: "Quiet cottage with valley views and trekking routes nearby.",
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
        price: 2100,
        location: "Mussoorie, Uttarakhand",
        country: "India",
    },
    {
        title: "Riverside Retreat",
        description: "Wooden retreat beside river with bonfire and stargazing.",
        image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
        price: 2300,
        location: "Rishikesh, Uttarakhand",
        country: "India",
    },
    {
        title: "Island Beach Hut",
        description: "Simple beach hut with direct access to white sand beach.",
        image: "https://images.unsplash.com/photo-1470246973918-29a93221c455",
        price: 1900,
        location: "Havelock Island, Andaman",
        country: "India",
    },
    {
        title: "Forest Eco Lodge",
        description: "Eco-friendly stay in the middle of lush forest trails.",
        image: "https://images.unsplash.com/photo-1448375240586-882707db888b",
        price: 2500,
        location: "Coorg, Karnataka",
        country: "India",
    },
    {
        title: "Hilltop Glass House",
        description: "Panoramic hill views from a modern glass house stay.",
        image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
        price: 3600,
        location: "Nainital, Uttarakhand",
        country: "India",
    },
    {
        title: "Temple Town Homestay",
        description: "Traditional homestay close to heritage temples and markets.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
        price: 1300,
        location: "Madurai, Tamil Nadu",
        country: "India",
    },
    {
        title: "Rainforest Treehouse",
        description: "Unique treehouse experience in dense rainforest surroundings.",
        image: "https://images.unsplash.com/photo-1472224371017-08207f84aaae",
        price: 2800,
        location: "Wayanad, Kerala",
        country: "India",
    },
    {
        title: "Luxury Farm Villa",
        description: "Spacious farm villa with organic meals and open lawns.",
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
        price: 3900,
        location: "Nashik, Maharashtra",
        country: "India",
    },
    {
        title: "Beachfront Studio",
        description: "Compact studio apartment just steps away from the beach.",
        image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        price: 1700,
        location: "Pondicherry",
        country: "India",
    },
    {
        title: "Royal Palace Room",
        description: "Stay in a palace-style room with classic decor and service.",
        image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a",
        price: 4600,
        location: "Udaipur, Rajasthan",
        country: "India",
    },
    {
        title: "Coffee Estate Bungalow",
        description: "Peaceful bungalow stay among coffee plantations.",
        image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
        price: 2400,
        location: "Chikmagalur, Karnataka",
        country: "India",
    },
    {
        title: "Urban Loft",
        description: "Stylish loft in a prime neighborhood with city skyline view.",
        image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80",
        price: 2600,
        location: "Mumbai, Maharashtra",
        country: "India",
    },
    {
        title: "Sunset Dune Camp",
        description: "Desert camp with camel rides and evening folk performances.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
        price: 1550,
        location: "Bikaner, Rajasthan",
        country: "India",
    },
    {
        title: "Rooftop Heritage Stay",
        description: "Old-city property with rooftop dining and monument views.",
        image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b",
        price: 2050,
        location: "Varanasi, Uttar Pradesh",
        country: "India",
    },
    {
        title: "Lakeside Wooden Cabin",
        description: "Quiet wooden cabin next to a calm lake and pine trees.",
        image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000",
        price: 2750,
        location: "Srinagar, Jammu and Kashmir",
        country: "India",
    },
    {
        title: "Artists Courtyard Home",
        description: "Colorful home with curated interiors and local art pieces.",
        image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
        price: 1850,
        location: "Kochi, Kerala",
        country: "India",
    },
    {
        title: "Skyline Penthouse",
        description: "Premium penthouse with private deck and panoramic skyline.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        price: 5200,
        location: "Gurugram, Haryana",
        country: "India",
    },
    {
        title: "River Delta Cottage",
        description: "Nature-focused cottage near mangroves and birdwatching spots.",
        image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
        price: 1950,
        location: "Sundarbans, West Bengal",
        country: "India",
    },
    {
        title: "Old Fort Guest House",
        description: "Historic guest house with stone architecture and local cuisine.",
        image: "https://images.unsplash.com/photo-1455587734955-081b22074882",
        price: 2250,
        location: "Gwalior, Madhya Pradesh",
        country: "India",
    }
];

module.exports = { data: sampleListing };
